### ISSUE TITLE
PRACTICA DE RELACIONES 

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/practica-de-relaciones-equipo-saul-lopez-bautista#1]
[Practica de Relaciones .pdf](https://github.com/SistemasTecTlaxiaco/practica-de-relaciones-equipo-saul-lopez-bautista/files/7316063/Practica.de.Relaciones.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
